name: 同步 ParaTranz 的翻譯

on:
  schedule:
    - cron: '0/15 * * * *'  # 每 15 分鐘執行一次
  workflow_dispatch:      # 手動觸發

jobs:
  download_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: ParaTranz - 下載翻譯
      run: |
        python .github/scripts/paratranz_downloader.py
      env:
          PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}
          FILE_ID: ${{ secrets.PARATRANZ_FILE_ID }}
          PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}

    - name: 同步提交
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "自動同步 ParaTranz 的最新翻譯"
