name: 同步 ParaTranz 的翻譯

on:
  schedule:
    - cron: '0/15 * * * *'  # 每 15 分鐘執行一次
  workflow_dispatch:      # 手動觸發

jobs:
  download_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: ParaTranz - 手動產生壓縮檔
      env:
          PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}
          PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
      run: |
        curl -L -X POST "https://paratranz.cn/api/projects/${PROJECT_ID}/artifacts/" \
          -H "Authorization: ${PARATRANZ_TOKEN}"
        sleep 3s

    - name: ParaTranz - 下載翻譯壓縮檔
      env:
          PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}
          PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
      run: |
        curl -L -X GET "https://paratranz.cn/api/projects/${PROJECT_ID}/artifacts/download" \
          -H "Authorization: ${PARATRANZ_TOKEN}" \
          -o artifacts.zip

    - name: 將 JSON 轉換成 Minecraft 格式
      run: |
        python .github/workflows/convert_json.py

    - name: 同步提交
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "自動同步 ParaTranz 的最新翻譯"